sudo: required
language: node_js
node_js:
  - "lts/*"
addons:
  chrome: stable
before_install:
  - if [[ `npm -v` != 6* ]]; then npm install -g npm@latest; fi
install:
  - npm ci
script:
  - npm test
  - npm run js-test-cloud
  - npm run release-coverage
cache:
  directories:
    - "node_modules"
git:
  depth: 3
